name: Develop CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  COMPOSER_MEMORY_LIMIT: -1
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: scrumproject_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Cache modificada con versión única (cambiar v100 si es necesario)
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-v100
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            public/build
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      # Extensions actualizadas para coincidir con local
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_pgsql, xml, curl, zip, ctype
          coverage: none
      
      - name: Install Node.js dependencies
        run: npm ci --prefer-offline
      
      - name: Build assets with Vite
        run: npm run build -- --mode=production
      
      - name: Copy .env
        run: cp .env.example .env
      
      # Comando con verbosidad aumentada (-vvv)
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --optimize-autoloader -vvv
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Set up environment for testing
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=scrumproject_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_URL=http://localhost" >> .env
      
      - name: Run migrations
        run: php artisan migrate --force
      
      - name: Run PHPUnit tests
        run: php artisan test --parallel

  dusk-tests:
    name: Dusk Browser Tests
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 30
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: scrumproject_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Cache modificada misma versión que en test
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-v100
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            public/build
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_pgsql, xml, curl, zip, ctype
          coverage: none

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            google-chrome-stable \
            xvfb \
            libglib2.0-0 \
            libnss3 \
            libx11-6
      
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      
      - name: Install Node.js dependencies
        run: npm ci --prefer-offline
      
      - name: Build assets with Vite
        run: npm run build -- --mode=production
      
      - name: Copy .env
        run: cp .env.example .env
      
      # Verbosidad aumentada también aquí
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --optimize-autoloader -vvv
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Set up environment for Dusk
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=scrumproject_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_URL=http://127.0.0.1:8000" >> .env
          echo "DUSK_DRIVER_URL=http://localhost:9515" >> .env
      
      - name: Run migrations
        run: php artisan migrate --force

      - name: Setup Chrome Driver
        run: |
          php artisan dusk:chrome-driver --detect
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 --whitelisted-ips &
          php artisan serve --port=8000 &
          sleep 5
      
      - name: Run Dusk Tests
        run: php artisan dusk --without-tty --parallel
        env:
          APP_URL: "http://127.0.0.1:8000"
          DISPLAY: :99

  deploy-to-develop:
    name: Deploy to Development
    needs: [test, dusk-tests]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false
      
      - name: Configure AWS credentials for S3 backend
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Terraform Init
        run: |
          cd terraform/environments/develop
          terraform init -reconfigure -input=false
      
      - name: Terraform Apply
        run: |
          cd terraform/environments/develop
          terraform apply -auto-approve -input=false -lock-timeout=10m
      
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.DEVELOP_EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" \
            --exclude='node_modules' \
            --exclude='.git' \
            --exclude='.env' \
            --delete \
            ./ $EC2_USER@$EC2_HOST:/var/www/scrumproject/
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'ENDSSH'
            cd /var/www/scrumproject
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart php-fpm nginx
          ENDSSH

  # Nuevo job añadido para limpiar caché (opcional)
  cleanup-cache:
    name: Cleanup Cache
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Delete Composer cache
        uses: actions/cache/delete@v1
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-v100