name: Production CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: scrumproject_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_pgsql, xml, curl, zip
      
      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build
      
      - name: Copy .env
        run: cp .env.example .env
      
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Set up environment for testing
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=scrumproject_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_URL=http://localhost" >> .env
      
      - name: Run migrations
        run: php artisan migrate --force
      
      - name: Run PHPUnit tests
        run: php artisan test
  
  dusk-tests:
    name: Dusk Browser Tests
    runs-on: ubuntu-latest
    needs: test
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: scrumproject_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_pgsql, xml, curl, zip

      - name: Install Chrome and X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb libglib2.0-0 libnss3 libx11-6

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          export DISPLAY=:99
      
      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build
      
      - name: Copy .env
        run: cp .env.example .env
      
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Set up environment for Dusk
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=scrumproject_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_URL=http://127.0.0.1:8000" >> .env
          echo "DUSK_DRIVER_URL=http://localhost:9515" >> .env
      
      - name: Run migrations
        run: php artisan migrate --force
      
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect
      
      - name: Start Chrome Driver
        run: |
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 --whitelisted-ips &
          sleep 5
        env:
          DISPLAY: :99
      
      - name: Start Laravel Server
        run: |
          php artisan serve --port=8000 &
          sleep 5
        env:
          APP_URL: "http://127.0.0.1:8000"
          DISPLAY: :99
      
      - name: Run Dusk Tests
        run: php artisan dusk --without-tty
        env:
          APP_URL: "http://127.0.0.1:8000"
          DISPLAY: :99
  
  deploy-to-production:
    name: Deploy to Production
    needs: [test, dusk-tests]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Configure AWS credentials for S3 backend
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Create S3 bucket for Terraform state if not exists
        run: |
          aws s3api head-bucket --bucket scrumproject-terraform-states 2>/dev/null || aws s3 mb s3://scrumproject-terraform-states --region us-west-2
      
      - name: Terraform Init
        run: |
          cd terraform/environments/production
          terraform init -reconfigure
      
      - name: Configure AWS credentials for infrastructure deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform Apply
        run: |
          cd terraform/environments/production
          terraform apply -auto-approve
      
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.PRODUCTION_EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Deploy using SSH
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'ENDSSH'
            cd /var/www/scrumproject
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          ENDSSH
  
  post-deploy-tests:
    name: Post-deployment Tests
    needs: deploy-to-production
    runs-on: ubuntu-latest
    
    steps:
      - name: Run end-to-end tests on production
        env:
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
        run: |
          # Simplemente verificamos que el sitio esté en línea
          curl -sSf $PRODUCTION_URL > /dev/null
          echo "Production site is up and running"